# SPDX-License-Identifier: Apache-2.0
name: "PR Formatting"
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

defaults:
  run:
    shell: bash

permissions:
  contents: read
  statuses: write

concurrency:
  group: pr-formatting-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  title-check:
    name: Title Check
    runs-on: hiero-client-sdk-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Check PR Title
        uses: step-security/conventional-pr-title-action@b54c0688e6fd1d221f8a936e05fdd82f500640d6 # v3.2.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
